auteurs= "Mathieu Bouchard, Luciano Barin-Cruz, Steve Maguire"
auteur1 = "Mathieu Bouchard"
auteur2 = "Luciano Barin-Cruz" 
auteur3 = "Steve Maguire"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/images/deviation.png"
description = "Description"
edition = "In press at"
format = "portrait"
indentation = "oui"
doi = "10.5465/amr.2020.0511"
licence = "CC BY-NC-SA"
logo = "/images/deviation.png"
marques = "crop"
mention = "PREPRINT"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = ""
titre = "Emotions and client participation in jurisdictional contestation"
poissonsBlancs = "/images/poissonsBlancs.png"
poissonsRouges = "/images/poissonsRouges.png"