auteur = "Mathieu Bouchard, Luciano Barin-Cruz, Steve Maguire"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = ""
description = "Description"
edition = "PREPRINT"
format = "portrait"
indentation = "oui"
isbn = "10.5465/amr.2020.0511"
licence = "CC BY-NC-SA"
logo = "deviation.png"
marques = "crop"
mention = "PREPRINT"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = ""
titre = "Emotions and client participation in jurisdictional contestation"
